# Generated by Django 4.2.5 on 2023-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
