# Generated by Django 4.2.5 on 2023-11-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_objective_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['year']},
        ),
    ]
